name: Dependabot Reviewer

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  review-and-merge-dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.2.0

      - name: Approve patch and minor updates
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve major updates of development dependencies
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:development' }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve -b "I'm **approving** this pull request because **it includes a major update of a dependency used only in development**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major updates of non-development dependencies
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "I'm **not approving** this PR because **it includes a major update of a dependency used in production**"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "requires-manual-qa"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Dependabot PR
        if: ${{ success() }}
        run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
